package com.vivekmlresearch.quantumapps.app;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.view.*;import android.widget.*;
import com.vivekmlresearch.quantumapps.core.*;import java.util.*;

public final class MainActivity extends Activity {
    private LinearLayout page; private final ArrayList<QuantumEngine.Gate> circuit=new ArrayList<>();private int n=2;
    private final int navy=Color.rgb(10,15,36),card=Color.rgb(24,34,67),cyan=Color.rgb(89,227,224);
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(navy);getWindow().setNavigationBarColor(navy);home();}
    private void screen(String title,String subtitle){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(navy);page=new LinearLayout(this);page.setOrientation(1);page.setPadding(22,26,22,40);scroll.addView(page);setContentView(scroll);label("⚛  QUANTUM UNIVERSE",17,cyan);label(title,27,Color.WHITE);label(subtitle,15,0xffafbfdd);space(12);}
    private void space(int dp){View v=new View(this);page.addView(v,new LinearLayout.LayoutParams(1,dp));}
    private void label(String t,int size,int color){TextView v=new TextView(this);v.setText(t);v.setTextSize(size);v.setTextColor(color);v.setPadding(3,7,3,9);page.addView(v);}
    private void button(String name,String description,Runnable action){LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(17,12,17,12);box.setBackgroundColor(card);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,6,0,6);page.addView(box,lp);TextView a=new TextView(this);a.setText(name+"  ›");a.setTextSize(18);a.setTextColor(Color.WHITE);box.addView(a);TextView b=new TextView(this);b.setText(description);b.setTextColor(0xffafbfdd);b.setTextSize(13);box.addView(b);box.setOnClickListener(v->action.run());}
    private void back(){button("← All labs","Return to the quantum-apps dashboard",this::home);}
    private void home(){screen("Explore quantum computing","Offline learning and experiments • v1.0");
        button("01  Learn","Qubits, superposition, entanglement and measurement",this::learn);
        button("02  Circuit Studio","Build circuits, inspect probabilities and export OpenQASM",this::studio);
        button("03  Algorithm Lab","Bell, GHZ, Grover search and Fourier transform",this::algorithms);
        button("04  Quantum AI","Feature maps and classical baseline",()->result("Quantum AI",Labs.qml()));
        button("05  Noise Laboratory","Bit and phase flips",()->result("Noise Laboratory",Labs.noise()));
        button("06  Quantum Security","Seeded BB84 protocol demonstration",()->result("Quantum Security",Labs.bb84()));
        button("07  Optimization","Small exact routing baseline",()->result("Optimization",Labs.optimization()));
        button("08  Benchmark Arena","Measure the local statevector engine",()->result("Benchmark Arena",Labs.benchmark()));
        button("09  Hardware Explorer","Why connectivity and fidelity matter",()->result("Hardware Explorer","Physical devices have restricted qubit connectivity and imperfect gates. A compiler maps logical gates to native gates and may insert SWAP operations.\n\nThis release simulates ideal local circuits; it does not connect to a quantum device."));
        button("10  About & scope","Methods, limitations and privacy",()->result("About","quantum-apps 1.0 • educational, fully offline. No accounts, analytics, network access or collection of personal data.\n\nThe local simulator supports 1–8 qubits. Algorithm and AI labs are small pedagogical demonstrations, not quantum-advantage claims. Code is designed for continued experiments."));}
    private void learn(){screen("Learn","Four ideas, each with an experiment you can run.");button("Qubit","|0⟩ and |1⟩ are basis states. A qubit can be a normalized combination α|0⟩ + β|1⟩.",()->result("Qubit",QuantumEngine.run(1,new ArrayList<>()).histogram()));button("Superposition","H|0⟩ has equal measurement probabilities.",()->result("Superposition",QuantumEngine.run(1,Arrays.asList(new QuantumEngine.Gate("H",0,-1))).histogram()));button("Entanglement","H on q0 followed by CNOT creates a Bell pair.",()->result("Entanglement",QuantumEngine.run(2,QuantumEngine.bell()).histogram()));button("Measurement","Probabilities are squared amplitude magnitudes; repeated shots sample those outcomes.",()->result("Measurement",QuantumEngine.run(2,QuantumEngine.bell()).histogram()));back();}
    private void algorithms(){screen("Algorithm Lab","Small circuits with inspectable outputs.");button("Bell pair","Two-qubit entanglement",()->result("Bell pair",QuantumEngine.run(2,QuantumEngine.bell()).state()+"\n"+QuantumEngine.run(2,QuantumEngine.bell()).histogram()));button("GHZ state","Three-qubit correlated state",()->result("GHZ",QuantumEngine.run(3,QuantumEngine.ghz()).histogram()));button("Grover search","Mark |11⟩ and amplify it with one iteration",()->result("Grover search",Labs.grover()));button("Quantum Fourier transform","Two-qubit example with complex amplitudes",()->result("QFT",Labs.qft()));button("Shor's algorithm","Concept and scope",()->result("Shor's algorithm","Shor's factoring algorithm uses modular exponentiation, phase estimation and a classical continued-fraction step. This release explains the concept; it does not implement Shor's algorithm or claim to factor RSA keys."));back();}
    private void studio(){screen("Circuit Studio","Local exact statevector • qubit 0 is least significant");button("Qubits: "+n+"  (tap to change)","Select one to eight qubits",()->{String[] opts={"1","2","3","4","5","6","7","8"};new AlertDialog.Builder(this).setTitle("Qubit count").setItems(opts,(d,w)->{n=w+1;circuit.clear();studio();}).show();});
        label("Gates: "+(circuit.isEmpty()?"(empty)":circuit.toString()),14,Color.WHITE);
        button("+ Add gate","H, X, Y, Z, S, T, CNOT, SWAP",this::gatePicker);
        button("↶ Remove last gate","Undo the latest step",()->{if(!circuit.isEmpty())circuit.remove(circuit.size()-1);studio();});
        button("▶ Run circuit","Show amplitudes and measurement probabilities",()->{try{QuantumEngine e=QuantumEngine.run(n,circuit);result("Circuit output",e.state()+"\nMEASUREMENT PROBABILITIES\n"+e.histogram());}catch(Exception ex){result("Circuit error",ex.getMessage());}});
        button("⇧ Export OpenQASM","Share source through an Android app",()->{Intent send=new Intent(Intent.ACTION_SEND);send.setType("text/plain");send.putExtra(Intent.EXTRA_TEXT,QuantumEngine.qasm(n,circuit));startActivity(Intent.createChooser(send,"Export circuit"));});
        button("Load Bell example","H(q0), CNOT(q0 → q1)",()->{n=2;circuit.clear();circuit.addAll(QuantumEngine.bell());studio();});back();}
    private void gatePicker(){String[] gates={"H","X","Y","Z","S","T","CNOT","SWAP"};new AlertDialog.Builder(this).setTitle("Select gate").setItems(gates,(d,g)->{String gate=gates[g];String[] qs=new String[n];for(int i=0;i<n;i++)qs[i]="q"+i;new AlertDialog.Builder(this).setTitle("Target qubit").setItems(qs,(d2,t)->{if(g<6){circuit.add(new QuantumEngine.Gate(gate,t,-1));studio();return;}new AlertDialog.Builder(this).setTitle(gate.equals("SWAP")?"Other qubit":"Control qubit").setItems(qs,(d3,c)->{if(c==t){Toast.makeText(this,"Choose different qubits",Toast.LENGTH_SHORT).show();return;}circuit.add(new QuantumEngine.Gate(gate,t,c));studio();}).show();}).show();}).show();}
    private void result(String title,String body){screen(title,"Interactive educational demonstration");TextView v=new TextView(this);v.setText(body);v.setTextColor(Color.WHITE);v.setTextSize(16);v.setTypeface(android.graphics.Typeface.MONOSPACE);v.setPadding(16,18,16,18);v.setBackgroundColor(card);page.addView(v);space(20);back();}
}
